 exports.profileRoute = require('./profiles.js')
 exports.userRoute = require('./users.js')
 exports.postRoute = require('./posts.js')
 exports.commentRoute = require('./comments.js')
 exports.securityRoute = require('./security.js')
 exports.feedRoute = require('./feed.js')